---
- hosts: all
  become: yes
  tasks:
  - name: add repository
    apt_repository:
      repo: ppa:openjdk-r/ppa
  - name: update the package 
    apt:
      update_cache: yes
  - name: install the java
    apt:
      name: openjdk-8-jdk
      state: present
  - name: install tomcat
    apt:
      name: tomcat7
      state: present
  - name: deployee the shopizer  war in webapps
    get_url:
      url: https://s3-us-west-2.amazonaws.com/ranjithkumarmca123rbucket/ROOT.war
      dest: /var/lib/tomcat7/webapps/ROOT.war
  - name: start the service 
    service: 
      name: tomcat7
      state: started
      enabled: yes