apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: shopizer-deploy
spec:
  replicas: 3
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: shopizer
    spec:
      containers:
      - name: shopizer
        image: amittapase/shopizer
        ports:
        - containerPort: 8080